# Generated by Django 2.2 on 2019-05-26 20:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloorLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.IntegerField()),
                ('level', models.IntegerField()),
                ('linja', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('building_name', models.CharField(max_length=30)),
            ],
        ),
    ]
